---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(htmltools)
library(here)
library(glue)

wiki_root_url <- "https://rupaulsdragrace.fandom.com/wiki/"
```

```{r initial url}
hytes_url <- glue("{wiki_root_url}Category:House_of_Hytes")
hytes_url
```

```{r}
hytes_results <-read_html(hytes_url)
hytes_results
```

```{r}
hytes_names <- hytes_results %>% 
  html_nodes(".category-page__member") %>% 
  html_text() %>% 
  str_replace_all( "[\t\n]" , "")
  hytes_names
```

```{r}
hytes_names_df <- as.data.frame(hytes_names)
```

```{r}
hytes_family_nodes <- expand.grid(hytes_names_df[[1]],hytes_names_df[[1]]) %>% 
  rename( "queen_1"=1
         ,"queen_2"=2) %>% 
  mutate( drag_family="Hytes"
         ,drag_mother=hytes_names_df[[1]][1] )%>%
  select(drag_family,drag_mother,queen_1,queen_2) %>% 
  filter(queen_1!=queen_2) 
hytes_family_nodes
```

# House of Minj
```{r This would be too much work }
minj_url <- glue("{wiki_root_url}Category:House_of_Minj")
minj_results <-read_html(minj_url)
minj_names <- minj_results %>% 
  html_nodes(".mw-parser-output") %>% 
  html_text()%>% 
  str_replace_all( "[\t\n]" , "") 
minj_names
```

# All Drag Families 
```{r}
drag_house_url <- glue("{wiki_root_url}Category:Queens_by_Drag_House")
drag_house_results <- read_html(drag_house_url)

drag_house_names <- drag_house_results %>% 
  html_nodes(".category-page__member-link") %>% 
  html_text() 

drag_house_urls <-  drag_house_results %>% 
  html_nodes(".category-page__member") %>% 
  html_text("href")%>% 
  str_replace_all( "[\t\n]" , "") %>% 
  str_replace_all(" ","_") %>% 
  as.data.frame() %>% 
  rename("url_end"=1)

drag_house_frame <- tibble(wiki_root_url,drag_house_urls) %>% 
  mutate(family_url=as.character(glue("{wiki_root_url}{url_end}"))
         , family_name=str_replace(url_end,"Category:","")
         , family_name=str_replace_all(family_name,"_"," ")
         ) %>% 
  filter(url_end!="Category:House_of_Stupi") # this is an empty page
  # Not elegant, need to do some more reading on how to handle and empty element.
  # So far this has only happened for the house of stupi... hoping it is a one off 
  # might have to make this a running list.... or maybe =check out the results 
  # one second..

```

```{r}
n_row <- nrow(drag_house_frame)


for(i in 1:n_row){

    print(i)
    print(family_name)
    results <- read_html(drag_house_frame$family_url[[i]] )
    result_string <-results %>% 
    html_nodes(".category-page__member") %>% 
    html_text() %>% 
    str_replace_all( "[\t\n]" , "")
  
 
  #print(drag_house_frame$family_url[[i]] )
  drag_house_frame$all_names[[i]]=result_string
    
  
  

  
}

```
 
